Added taxonom-pubmed config
togoid/togoid-config pull request #127
Opened 2022-08-25 02:01 UTC by dogrunjp

Added a taxonomy-pubmed config and related settings to Rakefile.

2022-08-25 05:02 UTC, sh-ikeda requested changes
コード内にいくつか変更を加えましたのでご確認のうえ反映をお願いいたします。
加えて、以下をお願いいたします。
- コンフィグのディレクトリ名が `taxonomy_id-pubmed` となっていますが、既に存在する taxonomy の config に合わせて、`taxonomy-pubmed` としてください。
- config.yaml 内の method の修正提案に問題がなければ、sample.txt をそれに合わせて更新してください。ファイル名は config.yaml 内の記述に合わせて `sample.tsv` としてください。(おそらく現状ではファイル名が一致していなくても問題は起きないと思いますが。)
- .gitignore はいじらないほうがいい気がします。

2022-08-26 03:37 UTC, dogrunjp commented
awkの記述を修正し、tsvの出力
を確認しました。

2022-08-26 05:35 UTC, sh-ikeda requested changes
二点修正しました、ご確認と反映をお願いいたします。

2022-08-26 05:35 UTC, sh-ikeda commented on config/taxonomy-pubmed/config.yaml
> +  method:  awk 'BEGIN{FS="\|"}$4!=0 {split($7,a," ");for(k in a){gsub(/\t/,"",$4); print a[k] "\t"  $4}}'${TOGOID_ROOT}/input/taxonomy/taxdump/citations.dmp
```suggestion
  method:  awk 'BEGIN{FS="\|"}$4!=0 {split($7,a," ");for(k in a){gsub(/\t/,"",$4); print a[k] "\t"  $4}}' ${TOGOID_ROOT}/input/taxonomy/taxdump/citations.dmp
```

2022-08-26 05:35 UTC, sh-ikeda commented on Rakefile
> +        sh "tar xzf #{INPUT_TAXONOMY_DIR}/taxdump.tar.gz -C #{INPUT_TAXONOMY_DIR}/taxdump/"
```suggestion
        sh "mkdir #{INPUT_TAXONOMY_DIR}/taxdump && tar xzf #{INPUT_TAXONOMY_DIR}/taxdump.tar.gz -C #{INPUT_TAXONOMY_DIR}/taxdump/"
```

2022-08-26 05:35 UTC, sh-ikeda commented on Rakefile
> +        sh "tar xzf #{INPUT_TAXONOMY_DIR}/taxdump.tar.gz -C #{INPUT_TAXONOMY_DIR}/taxdump/"
前回私が書いたところですが、tar の -C オプションの指定先は既存のディレクトリである必要があったので。

2022-08-26 05:40 UTC, dogrunjp commented
修正点、確認＆反映しました。ありがとうございます。

2022-08-26 05:41 UTC, sh-ikeda approved these changes

2022-08-26 05:42 UTC, merged

2022-08-26 05:46 UTC, sh-ikeda commented
マージしました、ご協力いただきありがとうございました！

@ktym 見落としているエラーがあるかもしれませんので、次回更新時にご留意いただければと思います。