pubchem_pathwayのpathwayIDとparticipantsの対応
togoid/togoid-config pull request #133
Opened 2022-09-08 08:25 UTC by nobusada-nbdc

小野さんと相談して入れてみるということで、ご確認お願いします。

2022-09-08 09:40 UTC, sh-ikeda requested changes
- pubchem_pathway-ensembl_gene というペアになっていますが、
  pubchem_pathway-pubchem_gene と pubchem_gene-ensembl_gene に分解してもよさそうに思います。
  pubchem_gene が誰も使わない ID であるならばこのままでもよさそうですが。
- pubchem_pathway-uniprot についても同様に、pubchem_pathway-pubchem_protein と pubchem_protein-uniprot への分解が検討できるかと思います。
- NCBI Protein は固有の ID を持っておらず、RefSeq や GenBank, UniProt の ID を使っています。そのため TogoID では単一の namespace として扱うのが難しく、取り扱わないことになったと思います。
  UniProt から RefSeq protein や INSDC の ID へのペアが既にあるので、特に NCBI Protein を使わないと得られない情報があるのでなければ今回のペア追加には含めなくてよいかと思います。
- SPARQL が重い件に関しては、pubchem ペアの作成に使っている既存のスクリプトが参考になりそうです。
  https://github.com/togoid/togoid-config/blob/main/config/pubchem_compound-chembl_compound/retrieve.sh
  ちょっと難解なので、山本さん、ご協力いただけますでしょうか。 @yayamamo 
- pubchem_pathway はまだ TogoID にないので、dataset.yaml への追加が必要です。

2022-09-08 09:40 UTC, sh-ikeda commented on config/pubchem_pathway-ensembl_gene/config.yaml
> +  reverse: TIO_000069
```suggestion
  forward: TIO_000084
  reverse: TIO_000085
```
gene は molecule でないので、TIO_000068 (pathway has participant molecule) やTIO_000069 (molecule participates in pathway) は使えないです。pathway has participant gene とかを後で新設しますので、まだないですがとりあえずこうしておきます。

2022-09-08 13:00 UTC, nobusada-nbdc commented on config/pubchem_pathway-ensembl_gene/config.yaml
> +  reverse: TIO_000069
承知しました

2022-09-13 02:40 UTC, nobusada-nbdc commented
dataset.yamlにpubchem_pathwayを追加しました。ご確認お願いします。 @sh-ikeda

2022-09-13 06:43 UTC, sh-ikeda commented
ありがとうございます。dataset.yaml は問題なさそうです。
最終的に必要なペアは
pubchem_pathway-ncbigene
pubchem_pathway-uniprot
pubchem_pathway-pubchem_compound
ということになったと思います。
pubchem_pathway-pubchem_gene は pubchem_pathway-ncbigene にリネームして、
またその他の不要になったディレクトリは削除をお願いいたします。

2022-09-13 07:22 UTC, nobusada-nbdc commented
ご確認ありがとうございます。
最終的に必要なペアは
pubchem_pathway-ensemble_gene
pubchem_pathway-uniprot
pubchem_pathway-pubchem_compound
だったと思います。
*pubchem_pathwayと関係づいているのはncbigeneではなくncbiproteinで、これは使わないということになったように思います。
上記３ペアを残して他を削除しました。

2022-09-13 07:41 UTC, sh-ikeda commented
pubchem pathway から直接つながっている pubchem gene (GID で始まるもの)が、実体としては NCBI gene であるので、直接の関係として取れるのは pubchem_pathway-ncbigene である、という理解だったのですが。Ensembl gene は pubchem gene からの closeMatch で取っていますよね。
participant として gene がつながっている例: https://pubchem.ncbi.nlm.nih.gov/rest/rdf/pathway/PWID40111.html

2022-09-13 08:03 UTC, nobusada-nbdc commented
申し訳ありません。そちらはすっかり頭から抜けていました。
pubchem_pathway-ncbigene　を追加しました。
pubchem_pathway-ensemble_gene　は削除しました。
ご確認よろしくお願いします。

2022-09-13 08:12 UTC, sh-ikeda commented
ありがとうございます。あとはクエリ実行のスクリプトについて山本さんとやり取りします。

2022-09-13 08:15 UTC, nobusada-nbdc commented
ありがとうございます。よろしくお願いします。

2022-09-14 07:06 UTC, yayamamo commented
諸々コミットしました！

2022-09-14 08:01 UTC, merged